FROM gradle:jdk21 as build

WORKDIR /usr/src/app

COPY * .
COPY gradle ./gradle
COPY src ./src
RUN ./gradlew clean
RUN ./gradlew build --stacktrace

FROM openjdk:21

WORKDIR /usr/src/client-demo
COPY --from=build /usr/src/app/build/libs/client-demo-0.0.1-SNAPSHOT.jar ./client-demo-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","client-demo-0.0.1-SNAPSHOT.jar"]
